/**
 * A small, data-first contract for the new UIUX previews.
 *
 * The existing data set intentionally stays untouched. This adapter makes the
 * renderer explicit about the semantic family, anatomy, states, and interaction
 * model that a preview is meant to communicate.
 */

const FAMILY_ALIASES = {
  "icon-button": "icon-button",
  "text-field": "input",
  "input": "input",
  "textarea": "textarea",
  "search": "search",
  "button": "button",
  "link": "link",
  "card": "card",
  "tabs": "tabs",
  "tab": "tabs",
  "tab-panel": "tabs",
  "modal": "modal",
  "dialog": "modal",
  "toast": "toast",
  "alert": "alert",
  "badge": "badge",
  "tag": "tag",
  "checkbox": "checkbox",
  "radio": "radio",
  "switch": "switch",
  "select": "select",
  "dropdown": "select",
  "combobox": "combobox",
  "menu": "menu",
  "tooltip": "tooltip",
  "accordion": "accordion",
  "disclosure": "accordion",
  "skeleton": "skeleton",
  "empty": "empty",
  "progress": "progress",
  "loader": "progress",
  "spinner": "progress",
  "drawer": "drawer",
  "sheet": "drawer",
  "table": "table",
  "data-table": "table",
  "list": "list",
  "grid": "grid",
  "pagination": "pagination",
  "breadcrumb": "breadcrumb",
  "steps": "steps",
  "stepper": "steps",
  "avatar": "avatar",
  "tooltip": "tooltip",
  "slider": "slider",
  "range": "slider",
  "calendar": "calendar",
  "date-picker": "calendar",
  "upload": "upload",
  "file-upload": "upload",
  "notification": "notification",
  "banner": "notification",
  "timeline": "timeline",
  "accordion": "accordion",
  "carousel": "carousel",
  "image-carousel": "carousel",
  "command-palette": "command",
  "command": "command",
  "code-block": "code",
  "code": "code",
  "layout-grid": "layout",
  "layout-sidebar": "layout",
  "layout-dashboard": "layout",
  "layout": "layout",
  "map": "map",
  "location": "map",
  "map-picker": "map",
  "language": "language",
  "locale": "language",
  "i18n": "language",
  "media": "media",
  "image": "media",
  "video": "media",
  "audio": "media",
  "player": "media",
  "security": "security",
  "auth": "security",
  "authentication": "security",
  "permission": "security",
  "chart": "chart",
  "graph": "chart",
  "visualization": "chart",
  "analytics": "chart",
  "motion": "motion",
  "animation": "motion",
  "transition": "motion",
  "toolbar": "toolbar",
  "top-navigation": "navigation",
  "bottom-navigation": "navigation",
  "navigation": "navigation",
  "sidebar": "navigation",
  "side-navigation": "navigation",
  "confirmation": "modal",
  "success-state": "notification",
  "error-state": "alert",
  "status-indicator": "notification",
  "form": "form",
  "form-item": "form",
  "form-group": "form",
  "filter-panel": "form",
  "sort-control": "select",
  "chat-bubble": "chat",
  "comment-box": "chat",
  "rating": "rating",
  "shopping-cart": "commerce",
  "text-content": "text",
  "text": "text",
  "icon-system": "primitive",
  "divider": "primitive",
  "panel": "card",
  "react-component": "react",
  "react-preview": "react",
  "mobile-preview": "mobile",
  "term-card": "dictionary",
  "editor": "editor",
  "help": "help",
  "a11y": "accessibility",
  "a11y-name": "accessibility",
  "a11y-contrast": "accessibility",
  "a11y-announcement": "accessibility",
  "a11y-structure": "accessibility",
  "a11y-target": "accessibility",
  "a11y-form": "accessibility",
  "a11y-testing": "accessibility",
  "i18n-text": "language",
  "i18n-plural": "language",
  "i18n-format": "language",
  "i18n-direction": "language",
  "i18n-search": "language",
  "i18n-compliance": "language",
  "file-action": "file",
  "file-preview": "media",
  "media-player": "media",
  "switcher": "switch",
  "barcode": "scan",
  "data-grid": "table",
  "layout-kanban": "layout",
  "layout-split": "layout",
  "layout-checkout": "layout",
  "popover": "tooltip",
  "pattern": "pattern",
};

const FAMILY_PATTERNS = [
  ["map", /(?:\b(map|maps|location|geolocation|geo|map picker)\b|地图|位置|定位|地理|坐标)/i],
  ["language", /(?:\b(language|locale|i18n|internationali[sz]ation|translation|locali[sz]ation)\b|多语言|语言|本地化|国际化|翻译)/i],
  ["media", /(?:\b(media|image|video|audio|player|thumbnail|file preview)\b|图片|视频|音频|媒体|播放器|缩略图)/i],
  ["security", /(?:\b(security|auth|authentication|authorization|password|passcode|permission|privacy|2fa|mfa|otp)\b|登录|认证|授权|密码|权限|安全|隐私|验证码)/i],
  ["chart", /(?:\b(chart|graph|visuali[sz]ation|analytics|metric|dashboard|trend)\b|趋势|图表|可视化|分析|指标)/i],
  ["motion", /(?:\b(motion|animation|animated|transition|easing|spring|keyframe|microinteraction)\b|动效|动画|过渡|缓动|关键帧|微交互)/i],
  ["text", /(?:\b(text hierarchy|heading|paragraph|caption|helper text|body copy)\b|文本层级|标题层级|段落文本|说明文本)/i],
  ["command", /\b(command|cmd|palette|shortcut|keyboard)\b/i],
  ["calendar", /\b(calendar|date|month|year|日期|日历|时间选择)\b/i],
  ["upload", /\b(upload|dropzone|file upload|上传|拖拽)\b/i],
  ["carousel", /\b(carousel|slider gallery|轮播|走马灯)\b/i],
  ["pagination", /\b(pagination|pager|分页)\b/i],
  ["breadcrumb", /\b(breadcrumb|面包屑)\b/i],
  ["steps", /\b(steps?|stepper|wizard|步骤|流程)\b/i],
  ["timeline", /\b(timeline|时间线|活动流)\b/i],
  ["table", /\b(table|data grid|数据表|数据网格)\b/i],
  ["grid", /\b(grid|gallery|网格|画廊)\b/i],
  ["list", /\b(list|feed|列表|清单)\b/i],
  ["combobox", /\b(combo(box)?|autocomplete|typeahead|自动完成)\b/i],
  ["select", /\b(select|dropdown|picker|选择器|下拉)\b/i],
  ["checkbox", /\b(check(box)?|复选|多选)\b/i],
  ["radio", /\b(radio|单选)\b/i],
  ["switch", /\b(switch|toggle|开关)\b/i],
  ["slider", /\b(slider|range|滑块|范围)\b/i],
  ["accordion", /\b(accordion|disclosure|折叠|手风琴)\b/i],
  ["tooltip", /\b(tooltip|popover|hint|悬浮提示|气泡)\b/i],
  ["drawer", /\b(drawer|sheet|侧栏|抽屉)\b/i],
  ["modal", /\b(modal|dialog|lightbox|弹窗|对话框|弹层)\b/i],
  ["toast", /\b(toast|snackbar|轻提示)\b/i],
  ["notification", /\b(notification|banner|通知|横幅)\b/i],
  ["alert", /\b(alert|warning|error message|警告|错误提示)\b/i],
  ["progress", /\b(progress|loading|spinner|进度|加载)\b/i],
  ["skeleton", /\b(skeleton|骨架)\b/i],
  ["empty", /\b(empty|no data|blank|空状态|无数据)\b/i],
  ["avatar", /\b(avatar|profile|用户头像)\b/i],
  ["badge", /\b(badge|status badge|徽标|状态标记)\b/i],
  ["tag", /\b(tag|chip|pill|标签|胶囊)\b/i],
  ["search", /\b(search|搜索)\b/i],
  ["textarea", /\b(textarea|multiline|多行输入)\b/i],
  ["input", /\b(input|text field|form field|输入框|输入)\b/i],
  ["icon-button", /\b(icon button|图标按钮)\b/i],
  ["link", /\b(link|anchor|链接)\b/i],
  ["button", /\b(button|cta|action|按钮)\b/i],
  ["tabs", /\b(tabs?|tab panel|segmented|标签页|标签面板|分段)\b/i],
  ["card", /\b(card|tile|panel|卡片|信息块)\b/i],
  ["menu", /\b(menu|context menu|菜单)\b/i],
  ["code", /\b(code|editor|markdown|代码|编辑器)\b/i],
  ["layout", /\b(layout|shell|sidebar|dashboard|布局|侧边栏)\b/i],
];

const ANATOMY_BY_FAMILY = {
  button: ["label", "action", "focus ring"],
  "icon-button": ["icon", "accessible label", "focus ring"],
  input: ["label", "input", "clear affordance", "helper/error"],
  textarea: ["label", "multiline input", "character count"],
  search: ["search icon", "input", "clear affordance"],
  link: ["label", "destination affordance", "visited/focus state"],
  card: ["media or icon", "content", "metadata", "action"],
  tabs: ["tab list", "active indicator", "tab panel"],
  modal: ["scrim", "dialog surface", "title", "body", "actions", "close"],
  toast: ["status icon", "message", "dismiss affordance"],
  alert: ["severity icon", "message", "optional action"],
  notification: ["title", "message", "action", "dismiss"],
  badge: ["label", "tone"],
  tag: ["label", "remove affordance"],
  checkbox: ["control", "label", "description"],
  radio: ["control", "label", "description"],
  switch: ["track", "thumb", "label"],
  select: ["label", "value", "chevron", "option list"],
  combobox: ["label", "input", "suggestion list"],
  menu: ["trigger", "menu surface", "items"],
  tooltip: ["anchor", "content", "pointer"],
  accordion: ["trigger", "chevron", "content panel"],
  skeleton: ["placeholder blocks", "loading cue"],
  empty: ["illustration", "title", "description", "recovery action"],
  progress: ["track", "fill", "status label"],
  drawer: ["scrim", "drawer surface", "header", "content", "close"],
  table: ["header row", "body rows", "status/action cells"],
  list: ["row", "primary text", "metadata", "row action"],
  grid: ["grid tracks", "items", "selection/action"],
  pagination: ["previous", "page items", "next"],
  breadcrumb: ["ancestor links", "separator", "current page"],
  steps: ["step indicator", "label", "connector"],
  avatar: ["image or initials", "status indicator"],
  slider: ["track", "thumb", "value label"],
  calendar: ["month header", "weekday row", "day cells"],
  upload: ["dropzone", "file list", "progress/action"],
  timeline: ["timestamp", "marker", "content"],
  carousel: ["viewport", "slides", "pagination", "controls"],
  command: ["search input", "result groups", "keyboard hint"],
  code: ["toolbar", "code surface", "line numbers"],
  layout: ["navigation", "content surface", "responsive boundary"],
  map: ["map viewport", "search or location control", "zoom controls", "pin/marker"],
  language: ["locale trigger", "language options", "current locale", "direction/mode"],
  media: ["media viewport", "transport controls", "timeline/progress", "metadata"],
  security: ["identity field", "credential control", "trust/recovery affordance", "status"],
  chart: ["chart viewport", "axes/grid", "data marks", "legend/tooltip"],
  motion: ["trigger state", "motion timeline", "easing curve", "reduced-motion fallback"],
  toolbar: ["tool groups", "active tool", "separator", "overflow menu"],
  navigation: ["brand or context", "navigation items", "current location", "responsive overflow"],
  form: ["field label", "control", "validation/help", "submit action"],
  chat: ["author/avatar", "message body", "timestamp", "reply/action"],
  rating: ["rating scale", "selected value", "label/help", "reset affordance"],
  commerce: ["product or cart item", "quantity", "price/summary", "checkout action"],
  text: ["content hierarchy", "line measure", "emphasis", "reading order"],
  primitive: ["visual primitive", "alignment boundary", "semantic label"],
  react: ["component boundary", "provider/context", "loading/error", "composition"],
  mobile: ["device frame", "gesture/action", "safe area", "system feedback"],
  dictionary: ["term", "plain-language definition", "alias", "related term"],
  editor: ["editor toolbar", "editable surface", "selection/state", "preview/output"],
  help: ["question/context", "support content", "search/navigation", "recovery path"],
  accessibility: ["semantic role", "focus/announcement", "contrast/target", "verification"],
  file: ["file identity", "status", "file action", "recovery affordance"],
  scan: ["capture viewport", "scan target", "permission/status", "result action"],
  pattern: ["task context", "content steps", "current state", "next action"],
  generic: ["primary content", "supporting detail", "action"],
};

const INTERACTION_BY_FAMILY = {
  button: "press → action feedback",
  "icon-button": "press or keyboard activation → action feedback",
  input: "focus → edit → validation",
  textarea: "focus → multiline edit → validation",
  search: "type → filter → clear",
  link: "hover/focus → navigate",
  card: "hover/focus → inspect → open detail",
  tabs: "select tab → update tab panel",
  modal: "open → focus trap → confirm/cancel → close",
  toast: "action → announce → timeout/dismiss",
  alert: "announce → optional recovery action",
  notification: "open/read → action/dismiss",
  badge: "reflect status; no primary action",
  tag: "select/remove",
  checkbox: "toggle selected state",
  radio: "choose one option",
  switch: "toggle setting",
  select: "open list → choose option",
  combobox: "type → filter suggestions → choose",
  menu: "open trigger → choose item → close",
  tooltip: "hover/focus anchor → reveal context",
  accordion: "toggle disclosure",
  skeleton: "loading → content replacement",
  empty: "recover → retry/create/navigate",
  progress: "progress updates → completion/error",
  drawer: "open → focus trap → close",
  table: "scan → sort/filter/select row",
  list: "scan → select/open row",
  grid: "scan → select/open item",
  pagination: "choose page → update results",
  breadcrumb: "choose ancestor → navigate",
  steps: "advance/back → update progress",
  avatar: "hover/focus → identify user",
  slider: "drag/arrow keys → update value",
  calendar: "navigate month → choose day",
  upload: "drop/select file → upload/progress",
  timeline: "scan chronological events",
  carousel: "next/previous → change slide",
  command: "open → type → execute command",
  code: "read/copy/edit code",
  layout: "resize/collapse navigation → preserve content",
  map: "search or pan map → inspect location → choose marker",
  language: "open locale menu → choose language → update copy/direction",
  media: "play/pause → seek timeline → adjust media state",
  security: "enter credential → verify identity → recover or continue",
  chart: "hover mark → inspect value → change range/filter",
  motion: "trigger state → play transition → settle or reduce motion",
  toolbar: "choose tool → update active state → overflow when needed",
  navigation: "choose destination → update current location → preserve context",
  form: "focus field → validate → submit or recover",
  chat: "compose → send → read/reply",
  rating: "choose score → communicate value → optionally reset",
  commerce: "adjust quantity → recalculate total → checkout",
  text: "scan hierarchy → read content → follow inline affordance",
  primitive: "compose primitive → align → preserve semantics",
  react: "mount boundary → resolve loading/error → compose children",
  mobile: "gesture/tap → update device state → preserve safe area",
  dictionary: "inspect term → compare alias → open related definition",
  editor: "edit selection → update preview → copy/publish",
  help: "search question → inspect guidance → recover or contact support",
  accessibility: "navigate semantic structure → announce state → verify result",
  file: "select file → apply action → confirm or recover",
  scan: "grant permission → scan target → review result",
  pattern: "start task → progress through context → complete or recover",
  generic: "inspect → open detail",
};

function clean(value) {
  return String(value || "").trim();
}

export function getPreviewFamily(item = {}) {
  const previewTokens = clean(item.previewBase || item.preview || item.previewId)
    .toLowerCase()
    .split(":")
    .map((token) => token.trim())
    .filter(Boolean);
  const explicit = previewTokens[0] || "";
  for (const token of previewTokens.slice().reverse()) {
    if (FAMILY_ALIASES[token]) return FAMILY_ALIASES[token];
  }
  if (FAMILY_ALIASES[explicit]) return FAMILY_ALIASES[explicit];

  const haystack = [
    item.id,
    item.title,
    item.english,
    item.group,
    item.docGroup,
    item.category,
    item.summary,
    item.plain,
  ]
    .map(clean)
    .join(" ");

  for (const [family, pattern] of FAMILY_PATTERNS) {
    if (pattern.test(haystack)) return family;
  }

  if (item.category === "layouts") return "layout";
  if (item.category === "states") return "notification";
  if (item.category === "patterns") return "card";
  if (item.category === "styles") return "layout";
  if (item.category === "react") return "react";
  if (item.category === "mobile") return "mobile";
  if (item.category === "dictionary") return "dictionary";
  if (item.category === "accessibility") return "accessibility";
  return "pattern";
}

export function createUiuxComponentSpec(item = {}) {
  const family = getPreviewFamily(item);
  const variants = Array.isArray(item.variants) ? item.variants.filter(Boolean) : [];
  const states = Array.isArray(item.states) ? item.states.filter(Boolean) : [];
  const useCases = Array.isArray(item.useCases) ? item.useCases.filter(Boolean) : [];
  return {
    id: clean(item.id) || "uiux-item",
    title: clean(item.title) || clean(item.english) || "UI component",
    english: clean(item.english) || clean(item.title) || "UI component",
    family,
    category: clean(item.category) || "components",
    group: clean(item.group || item.docGroup),
    summary: clean(item.summary || item.description || item.plain),
    anatomy: ANATOMY_BY_FAMILY[family] || ANATOMY_BY_FAMILY.generic,
    states: states.length ? states : ["default", "hover", "focus", "disabled"],
    variants: variants.length ? variants : ["default", "compact", "emphasis"],
    interactionModel: INTERACTION_BY_FAMILY[family] || INTERACTION_BY_FAMILY.generic,
    useCases,
    raw: item,
  };
}

export function getFamilyAnatomy(family) {
  return ANATOMY_BY_FAMILY[family] || ANATOMY_BY_FAMILY.generic;
}

export const UIUX_RENDERER_FAMILIES = Object.freeze(
  [...new Set(["generic", "pattern", ...Object.values(FAMILY_ALIASES), ...FAMILY_PATTERNS.map(([family]) => family)])],
);
