export const sections = [
  { id: "components", label: "组件" },
  { id: "layouts", label: "布局" },
  { id: "styles", label: "样式" },
  { id: "motion", label: "动效" },
  { id: "patterns", label: "场景" },
  { id: "dictionary", label: "词典" },
];

const commonNotes = {
  accessibility: ["可用键盘访问", "焦点状态清楚", "不要只靠颜色表达状态"],
  do: ["名称写清楚", "状态要能被看懂", "和周围内容保持一致"],
  dont: ["不要让它看起来可点却不能点", "不要把同一层级做得都很抢眼", "不要省略错误或禁用原因"],
};

function item(data) {
  return {
    aliases: [],
    tags: [],
    variants: [],
    states: [],
    useCases: [],
    do: commonNotes.do,
    dont: commonNotes.dont,
    accessibility: commonNotes.accessibility,
    related: [],
    preview: "generic",
    comparison: null,
    ...data,
  };
}

const coreItems = [
  item({
    id: "button",
    title: "按钮",
    english: "Button",
    category: "components",
    group: "操作",
    summary: "触发一个操作或提交表单。",
    plain: "按钮让用户执行一个明确动作，比如保存、继续、购买或删除。",
    aliases: ["CTA", "提交按钮", "操作按钮"],
    tags: ["表单", "购买", "后台", "移动端"],
    variants: ["主按钮", "次按钮", "描边按钮", "文字按钮", "图标按钮", "危险按钮"],
    states: ["默认", "悬停", "按下", "聚焦", "禁用", "加载中", "成功"],
    useCases: ["登录", "保存", "提交", "购买", "删除", "继续"],
    do: ["一个区域只突出一个主要按钮", "危险操作要明确提示", "按钮文字写清动作"],
    dont: ["不要把所有按钮都做成主按钮", "不要只放图标却没有说明", "不要让禁用按钮没有原因"],
    related: ["link", "icon-button", "menu", "modal"],
    preview: "button",
    comparison: { left: "按钮", right: "链接", note: "按钮负责执行动作，链接负责跳到位置或资源。" },
  }),
  item({
    id: "text-field",
    title: "输入框",
    english: "Text Field",
    category: "components",
    group: "输入",
    summary: "让用户输入或编辑信息。",
    plain: "输入框通常出现在登录、搜索、表单填写和设置页面里。",
    aliases: ["文本框", "输入栏"],
    tags: ["表单", "登录", "设置"],
    variants: ["单行输入", "带图标输入", "带清除按钮", "错误输入", "只读输入"],
    states: ["默认", "聚焦", "已填写", "错误", "禁用"],
    useCases: ["填写姓名", "输入邮箱", "搜索关键词", "输入验证码"],
    related: ["textarea", "search", "password-field", "select"],
    preview: "text",
    comparison: { left: "输入框", right: "选择器", note: "输入框适合自由填写，选择器适合从固定选项中选。" },
  }),
  item({
    id: "modal",
    title: "弹窗",
    english: "Modal",
    category: "components",
    group: "反馈",
    summary: "盖在页面上的重要提示或任务。",
    plain: "弹窗会打断当前流程，通常用于确认删除、支付、退出登录等关键操作。",
    aliases: ["Dialog", "对话框", "确认框"],
    tags: ["确认", "危险操作", "表单"],
    variants: ["确认弹窗", "表单弹窗", "全屏弹窗", "底部弹窗"],
    states: ["打开", "关闭", "加载", "错误", "成功"],
    useCases: ["删除确认", "支付确认", "编辑资料", "登录提示"],
    dont: ["不要用弹窗展示普通提示", "不要一进入页面就弹出多个弹窗", "不要隐藏关闭入口"],
    related: ["toast", "alert", "drawer", "popover"],
    preview: "modal",
    comparison: { left: "弹窗", right: "Toast", note: "弹窗需要处理，Toast 只是短暂告诉用户结果。" },
  }),
  item({
    id: "toast",
    title: "Toast",
    english: "Toast",
    category: "components",
    group: "反馈",
    summary: "短暂出现的轻量提示。",
    plain: "Toast 通常出现在页面角落，告诉用户刚刚的操作结果，比如保存成功。",
    aliases: ["轻提示", "Snackbar"],
    tags: ["成功", "错误", "保存"],
    variants: ["成功提示", "错误提示", "可撤销提示", "带操作提示"],
    states: ["进入", "显示", "自动消失"],
    useCases: ["保存成功", "复制成功", "网络失败", "删除后撤销"],
    related: ["alert", "modal", "notification"],
    preview: "toast",
    comparison: { left: "Toast", right: "Alert", note: "Toast 短暂，Alert 更显眼也更持久。" },
  }),
  item({
    id: "card",
    title: "卡片",
    english: "Card",
    category: "components",
    group: "展示",
    summary: "把一组相关信息装在一起。",
    plain: "卡片像一个信息小盒子，常用于商品、文章、作品、模板和资料概览。",
    aliases: ["内容卡", "信息卡"],
    tags: ["展示", "电商", "文章"],
    variants: ["图片卡", "数据卡", "操作卡", "列表卡", "紧凑卡"],
    states: ["默认", "悬停", "选中", "加载中"],
    useCases: ["商品列表", "作品集", "文章推荐", "模板入口"],
    related: ["list", "table", "badge"],
    preview: "card",
    comparison: { left: "卡片", right: "列表", note: "卡片适合独立对象，列表适合连续浏览。" },
  }),
  item({
    id: "tabs",
    title: "标签页",
    english: "Tabs",
    category: "components",
    group: "导航",
    summary: "在同一区域切换不同内容。",
    plain: "标签页用于同一页面内的内容切换，比如详情、评论、参数。",
    aliases: ["Tab", "页签"],
    tags: ["导航", "详情页", "设置"],
    variants: ["下划线标签", "胶囊标签", "垂直标签", "可滚动标签"],
    states: ["默认", "选中", "悬停", "禁用"],
    useCases: ["商品详情", "设置分组", "数据视图", "文档切换"],
    related: ["segmented-control", "sidebar", "breadcrumb"],
    preview: "tabs",
    comparison: { left: "标签页", right: "分段控制", note: "标签页切换大内容，分段控制常切换视图模式。" },
  }),
  item({
    id: "icon-button",
    title: "图标按钮",
    english: "Icon Button",
    category: "components",
    group: "操作",
    summary: "用图标表示一个动作。",
    plain: "图标按钮节省空间，但需要让用户能看懂含义。",
    aliases: ["工具按钮"],
    tags: ["工具栏", "移动端", "后台"],
    variants: ["圆形按钮", "方形按钮", "透明按钮", "危险图标按钮"],
    states: ["默认", "悬停", "按下", "聚焦", "禁用"],
    useCases: ["搜索", "关闭", "收藏", "分享", "删除"],
    related: ["button", "toolbar", "tooltip"],
    preview: "icon-button",
  }),
  item({
    id: "link",
    title: "链接",
    english: "Link",
    category: "components",
    group: "操作",
    summary: "跳转到另一个位置或资源。",
    plain: "链接用于导航，不适合承担保存、提交这类动作。",
    tags: ["导航", "文章", "帮助"],
    variants: ["正文链接", "导航链接", "外部链接", "返回链接"],
    states: ["默认", "悬停", "访问过", "聚焦"],
    useCases: ["查看详情", "打开帮助", "跳到页面", "下载资源"],
    related: ["button", "breadcrumb", "menu"],
    preview: "link",
  }),
  item({
    id: "menu",
    title: "菜单",
    english: "Menu",
    category: "components",
    group: "操作",
    summary: "展开一组可选操作。",
    plain: "菜单把不常用或次要动作收起来，避免页面太挤。",
    tags: ["更多", "工具栏", "右键"],
    variants: ["下拉菜单", "右键菜单", "级联菜单", "操作菜单"],
    states: ["关闭", "打开", "选中", "禁用项"],
    useCases: ["更多操作", "排序方式", "账户菜单", "右键操作"],
    related: ["dropdown", "context-menu", "toolbar"],
    preview: "menu",
  }),
  item({
    id: "dropdown",
    title: "下拉菜单",
    english: "Dropdown",
    category: "components",
    group: "操作",
    summary: "从多个选项里选一个。",
    plain: "下拉菜单适合选项较多但不需要一直展示的场景。",
    tags: ["筛选", "表单", "设置"],
    variants: ["单选下拉", "多选下拉", "带搜索下拉", "分组下拉"],
    states: ["关闭", "打开", "已选择", "错误", "禁用"],
    useCases: ["选择城市", "选择排序", "选择状态", "切换语言"],
    related: ["select", "menu", "filter-panel"],
    preview: "dropdown",
  }),
  item({
    id: "checkbox",
    title: "复选框",
    english: "Checkbox",
    category: "components",
    group: "输入",
    summary: "可以多选或独立开关一个条件。",
    plain: "复选框适合同时选择多个条件，比如筛选品牌和价格范围。",
    tags: ["表单", "筛选", "设置"],
    variants: ["未选", "已选", "半选", "禁用"],
    states: ["默认", "选中", "聚焦", "禁用"],
    useCases: ["同意协议", "多选筛选", "批量选择", "开关偏好"],
    related: ["radio", "switch", "filter-panel"],
    preview: "checkbox",
  }),
  item({
    id: "radio",
    title: "单选按钮",
    english: "Radio",
    category: "components",
    group: "输入",
    summary: "多个选项只能选一个。",
    plain: "单选按钮适合选项少且需要全部露出的选择。",
    tags: ["表单", "设置", "问卷"],
    variants: ["横向单选", "纵向单选", "卡片单选"],
    states: ["默认", "选中", "聚焦", "禁用"],
    useCases: ["选择性别", "选择配送方式", "选择支付方式", "问卷题"],
    related: ["checkbox", "segmented-control", "select"],
    preview: "radio",
  }),
  item({
    id: "switch",
    title: "开关",
    english: "Switch",
    category: "components",
    group: "输入",
    summary: "立即开启或关闭某个功能。",
    plain: "开关像灯的开关，适合状态会马上生效的设置。",
    tags: ["设置", "移动端", "偏好"],
    variants: ["开启", "关闭", "禁用", "加载"],
    states: ["默认", "开启", "聚焦", "禁用"],
    useCases: ["开启通知", "减少动效", "深色模式", "自动保存"],
    related: ["checkbox", "settings-page"],
    preview: "switch",
  }),
  item({
    id: "select",
    title: "选择器",
    english: "Select",
    category: "components",
    group: "输入",
    summary: "在表单中选择固定答案。",
    plain: "选择器比自由输入更可控，适合国家、状态、角色这类固定选项。",
    tags: ["表单", "设置"],
    variants: ["单选", "多选", "可搜索", "分组选项"],
    states: ["默认", "打开", "已选择", "错误", "禁用"],
    useCases: ["选择国家", "选择角色", "选择订单状态", "选择分类"],
    related: ["dropdown", "radio", "autocomplete"],
    preview: "select",
  }),
  item({
    id: "table",
    title: "表格",
    english: "Table",
    category: "components",
    group: "展示",
    summary: "用行和列对比数据。",
    plain: "表格适合需要横向比较多个字段的信息，比如订单、成员、账单。",
    tags: ["后台", "数据", "列表"],
    variants: ["基础表格", "可排序表格", "可筛选表格", "可编辑表格"],
    states: ["加载", "空状态", "选中行", "错误"],
    useCases: ["订单列表", "成员管理", "财务明细", "任务清单"],
    related: ["data-grid", "list", "pagination"],
    preview: "table",
  }),
  item({
    id: "badge",
    title: "徽标",
    english: "Badge",
    category: "components",
    group: "展示",
    summary: "小数字或状态标记。",
    plain: "徽标用于提醒数量、状态或类别，比如未读消息数。",
    tags: ["通知", "状态", "分类"],
    variants: ["数字徽标", "状态徽标", "点状徽标", "标签徽标"],
    states: ["默认", "成功", "警告", "错误"],
    useCases: ["未读数", "新功能", "订单状态", "会员等级"],
    related: ["tag", "notification", "avatar"],
    preview: "badge",
  }),
  item({
    id: "tooltip",
    title: "提示气泡",
    english: "Tooltip",
    category: "components",
    group: "展示",
    summary: "悬停时出现的小解释。",
    plain: "提示气泡用于解释图标或短标签，不适合放重要内容。",
    tags: ["帮助", "图标", "说明"],
    variants: ["顶部提示", "底部提示", "带快捷键提示"],
    states: ["隐藏", "显示"],
    useCases: ["解释图标", "显示完整文本", "说明快捷键"],
    related: ["popover", "icon-button", "help-text"],
    preview: "tooltip",
  }),
  item({
    id: "accordion",
    title: "手风琴",
    english: "Accordion",
    category: "components",
    group: "展示",
    summary: "展开或收起一段内容。",
    plain: "手风琴把长内容分段折叠，让用户按需展开。",
    tags: ["FAQ", "设置", "帮助"],
    variants: ["单项展开", "多项展开", "带图标展开"],
    states: ["收起", "展开", "禁用"],
    useCases: ["常见问题", "说明文档", "设置分组", "筛选项"],
    related: ["drawer", "tabs", "popover"],
    preview: "accordion",
  }),
  item({
    id: "skeleton",
    title: "骨架屏",
    english: "Skeleton",
    category: "components",
    group: "反馈",
    summary: "内容加载前的占位形状。",
    plain: "骨架屏让用户知道页面正在加载，也暗示内容即将长什么样。",
    tags: ["加载", "列表", "性能"],
    variants: ["文字骨架", "卡片骨架", "头像骨架", "表格骨架"],
    states: ["加载中", "加载完成"],
    useCases: ["加载文章", "加载卡片", "加载表格", "加载资料"],
    related: ["spinner", "progress", "empty-state"],
    preview: "skeleton",
  }),
  item({
    id: "empty-state",
    title: "空状态",
    english: "Empty State",
    category: "components",
    group: "反馈",
    summary: "没有内容时的说明和下一步。",
    plain: "空状态告诉用户这里为什么没东西，以及接下来可以做什么。",
    tags: ["无数据", "引导", "错误"],
    variants: ["首次使用", "搜索无结果", "权限为空", "加载失败"],
    states: ["空", "可创建", "可重试"],
    useCases: ["没有订单", "没有收藏", "搜索无结果", "网络失败"],
    related: ["skeleton", "alert", "button"],
    preview: "empty",
  }),
  item({
    id: "progress",
    title: "进度条",
    english: "Progress Bar",
    category: "components",
    group: "反馈",
    summary: "显示任务完成到哪一步。",
    plain: "进度条适合上传、下载、安装、分步处理这类需要等待的任务。",
    tags: ["上传", "下载", "加载"],
    variants: ["确定进度", "不确定进度", "步骤进度"],
    states: ["进行中", "完成", "失败"],
    useCases: ["文件上传", "导出文件", "安装更新", "问卷进度"],
    related: ["spinner", "skeleton", "stepper"],
    preview: "progress",
  }),
  item({
    id: "drawer",
    title: "抽屉",
    english: "Drawer",
    category: "components",
    group: "导航",
    summary: "从侧边滑出的面板。",
    plain: "抽屉常用于移动端导航、筛选器和临时详情面板。",
    tags: ["导航", "筛选", "移动端"],
    variants: ["左侧抽屉", "右侧抽屉", "底部抽屉"],
    states: ["关闭", "打开", "加载", "禁用"],
    useCases: ["菜单导航", "筛选商品", "查看详情", "移动端设置"],
    related: ["modal", "sidebar", "filter-panel"],
    preview: "drawer",
  }),

  item({
    id: "single-column",
    title: "单列布局",
    english: "Single Column",
    category: "layouts",
    group: "阅读",
    summary: "内容从上到下排列。",
    plain: "单列布局适合文章、说明页和步骤较少的页面。",
    tags: ["文章", "说明页", "移动端"],
    useCases: ["博客文章", "帮助文档", "公告", "登录页"],
    related: ["two-column", "sticky-header"],
    preview: "layout-single",
  }),
  item({
    id: "two-column",
    title: "双栏布局",
    english: "Two Column",
    category: "layouts",
    group: "详情",
    summary: "左右两侧分别承载主内容和辅助内容。",
    plain: "双栏布局常见于详情页、设置页和文档页。",
    tags: ["详情", "设置", "文档"],
    useCases: ["文章目录", "商品详情", "账户设置", "文档阅读"],
    related: ["single-column", "sidebar-layout"],
    preview: "layout-two",
  }),
  item({
    id: "sidebar-layout",
    title: "侧边栏布局",
    english: "Sidebar Layout",
    category: "layouts",
    group: "导航",
    summary: "一侧固定导航，另一侧显示内容。",
    plain: "侧边栏布局适合内容较多、需要频繁切换栏目的网站。",
    tags: ["后台", "文档", "工具"],
    useCases: ["后台系统", "文档站", "设置中心", "邮箱"],
    related: ["dashboard", "master-detail"],
    preview: "layout-sidebar",
  }),
  item({
    id: "dashboard",
    title: "仪表盘布局",
    english: "Dashboard",
    category: "layouts",
    group: "数据",
    summary: "把关键数据和操作集中展示。",
    plain: "仪表盘适合运营后台、数据分析和管理面板。",
    tags: ["后台", "数据", "运营"],
    useCases: ["销售看板", "项目状态", "运营数据", "监控面板"],
    related: ["table", "card-grid", "data-grid"],
    preview: "layout-dashboard",
  }),
  item({
    id: "card-grid",
    title: "卡片网格",
    english: "Card Grid",
    category: "layouts",
    group: "展示",
    summary: "用网格展示多个对象。",
    plain: "卡片网格适合浏览商品、模板、作品和文章。",
    tags: ["商品", "作品", "模板"],
    useCases: ["商品列表", "模板库", "作品集", "课程列表"],
    related: ["card", "masonry", "list"],
    preview: "layout-grid",
  }),
  item({
    id: "feed",
    title: "信息流布局",
    english: "Feed",
    category: "layouts",
    group: "内容",
    summary: "按时间或推荐顺序连续展示内容。",
    plain: "信息流让用户不断往下浏览，常见于社区、新闻和动态页。",
    tags: ["社交", "新闻", "动态"],
    useCases: ["朋友圈", "新闻流", "推荐内容", "评论流"],
    related: ["list", "infinite-scroll"],
    preview: "layout-feed",
  }),
  item({
    id: "master-detail",
    title: "主从布局",
    english: "Master Detail",
    category: "layouts",
    group: "详情",
    summary: "左边列表，右边详情。",
    plain: "主从布局适合邮件、联系人、订单和文档浏览。",
    tags: ["邮箱", "订单", "文档"],
    useCases: ["邮箱", "订单管理", "联系人", "文件管理"],
    related: ["two-column", "sidebar-layout"],
    preview: "layout-master",
  }),
  item({
    id: "settings-page",
    title: "设置页",
    english: "Settings Page",
    category: "layouts",
    group: "设置",
    summary: "按分组管理偏好和账户信息。",
    plain: "设置页应该让用户快速找到要改的选项。",
    tags: ["账户", "偏好", "安全"],
    useCases: ["账户资料", "通知设置", "隐私设置", "安全设置"],
    related: ["form", "switch", "sidebar-layout"],
    preview: "layout-settings",
  }),
  item({
    id: "checkout-page",
    title: "结算页",
    english: "Checkout Page",
    category: "layouts",
    group: "电商",
    summary: "完成购买前的确认流程。",
    plain: "结算页需要清楚展示商品、地址、价格和付款方式。",
    tags: ["电商", "支付", "表单"],
    useCases: ["购物结算", "订阅购买", "票务支付"],
    related: ["shopping-cart", "form", "stepper"],
    preview: "layout-checkout",
  }),

  item({
    id: "radius",
    title: "圆角",
    english: "Border Radius",
    category: "styles",
    group: "形状",
    summary: "决定界面是锋利、柔和还是胶囊感。",
    plain: "小圆角更克制，大圆角更亲和，胶囊形常用于按钮和标签。",
    tags: ["形状", "按钮", "卡片"],
    variants: ["直角", "小圆角", "大圆角", "胶囊"],
    related: ["shadow", "card", "button"],
    preview: "style-radius",
  }),
  item({
    id: "shadow",
    title: "阴影",
    english: "Shadow",
    category: "styles",
    group: "层级",
    summary: "暗示元素是否浮在页面上。",
    plain: "阴影常用来表达浮层、卡片或弹窗的层级。",
    tags: ["层级", "卡片", "弹窗"],
    variants: ["无阴影", "轻阴影", "浮起", "强阴影"],
    related: ["card", "modal", "popover"],
    preview: "style-shadow",
  }),
  item({
    id: "spacing",
    title: "留白",
    english: "Spacing",
    category: "styles",
    group: "排版",
    summary: "用空白组织信息关系。",
    plain: "留白不是浪费空间，它让用户更快分清哪些内容属于一组。",
    tags: ["阅读", "排版", "密度"],
    variants: ["紧凑", "普通", "宽松"],
    related: ["density", "typography"],
    preview: "style-spacing",
  }),
  item({
    id: "typography",
    title: "字体层级",
    english: "Typography",
    category: "styles",
    group: "排版",
    summary: "用大小、粗细和行高建立阅读顺序。",
    plain: "好的字体层级会告诉用户先看标题，再看说明，再看操作。",
    tags: ["文字", "阅读", "标题"],
    variants: ["标题", "正文", "说明", "标签"],
    related: ["spacing", "color"],
    preview: "style-type",
  }),
  item({
    id: "color",
    title: "色彩",
    english: "Color",
    category: "styles",
    group: "视觉",
    summary: "表达品牌、状态和重点。",
    plain: "色彩可以突出重点，但状态不能只靠颜色表达。",
    tags: ["品牌", "状态", "强调"],
    variants: ["主色", "成功", "警告", "危险", "中性色"],
    related: ["contrast", "badge", "alert"],
    preview: "style-color",
  }),
  item({
    id: "density",
    title: "密度",
    english: "Density",
    category: "styles",
    group: "排版",
    summary: "决定页面信息是紧凑还是舒展。",
    plain: "高密度适合后台工具，低密度适合阅读和普通用户理解。",
    tags: ["后台", "阅读", "移动端"],
    variants: ["紧凑", "标准", "舒展"],
    related: ["spacing", "table", "dashboard"],
    preview: "style-density",
  }),
  item({
    id: "dark-mode",
    title: "暗色模式",
    english: "Dark Mode",
    category: "styles",
    group: "主题",
    summary: "在深色背景上重新组织颜色和层级。",
    plain: "暗色模式不是把颜色反过来，而是重新保证可读性和层级。",
    tags: ["主题", "可访问性"],
    variants: ["深色背景", "暗色浮层", "高对比"],
    related: ["contrast", "color"],
    preview: "style-dark",
  }),

  item({
    id: "hover-motion",
    title: "悬停反馈",
    english: "Hover Feedback",
    category: "motion",
    group: "反馈",
    summary: "提示这里可以操作。",
    plain: "悬停反馈通常用轻微变色、边框或上浮表示可点击。",
    tags: ["鼠标", "按钮", "卡片"],
    useCases: ["按钮悬停", "卡片悬停", "菜单项悬停"],
    related: ["press-motion", "button", "card"],
    preview: "motion-hover",
  }),
  item({
    id: "press-motion",
    title: "点击反馈",
    english: "Press Feedback",
    category: "motion",
    group: "反馈",
    summary: "让用户知道自己点到了。",
    plain: "点击反馈应该很快，通常在 100ms 内出现。",
    tags: ["按钮", "移动端", "触控"],
    useCases: ["按钮按下", "列表选中", "图标点击"],
    related: ["hover-motion", "button"],
    preview: "motion-press",
  }),
  item({
    id: "loading-motion",
    title: "加载动效",
    english: "Loading Motion",
    category: "motion",
    group: "加载",
    summary: "表达系统正在处理。",
    plain: "加载动效要让等待更可理解，但不要遮挡已有内容太久。",
    tags: ["等待", "进度", "骨架屏"],
    useCases: ["提交中", "加载列表", "上传文件"],
    related: ["skeleton", "spinner", "progress"],
    preview: "motion-loading",
  }),
  item({
    id: "success-motion",
    title: "成功反馈",
    english: "Success Feedback",
    category: "motion",
    group: "反馈",
    summary: "确认操作已经完成。",
    plain: "成功反馈可以是按钮文字改变、对勾出现或 Toast 提示。",
    tags: ["保存", "提交", "完成"],
    useCases: ["保存成功", "支付完成", "复制成功"],
    related: ["toast", "button", "progress"],
    preview: "motion-success",
  }),
  item({
    id: "error-motion",
    title: "错误反馈",
    english: "Error Feedback",
    category: "motion",
    group: "反馈",
    summary: "提醒用户需要修正。",
    plain: "错误反馈可以轻微抖动输入框，但必须配合文字说明。",
    tags: ["表单", "错误", "输入"],
    useCases: ["密码错误", "必填项为空", "上传失败"],
    related: ["text-field", "alert", "toast"],
    preview: "motion-error",
  }),
  item({
    id: "expand-motion",
    title: "展开收起",
    english: "Expand Collapse",
    category: "motion",
    group: "空间",
    summary: "表达信息层级变化。",
    plain: "展开收起适合把次要内容先藏起来，用户需要时再打开。",
    tags: ["手风琴", "详情", "筛选"],
    useCases: ["FAQ 展开", "筛选展开", "详情展开"],
    related: ["accordion", "drawer"],
    preview: "motion-expand",
  }),
  item({
    id: "reduced-motion",
    title: "减少动效",
    english: "Reduced Motion",
    category: "motion",
    group: "可访问性",
    summary: "减少非必要动画。",
    plain: "减少动效尊重用户偏好，降低眩晕和干扰。",
    tags: ["可访问性", "偏好", "设置"],
    useCases: ["系统偏好", "阅读模式", "动画较多的产品"],
    related: ["switch", "accessibility"],
    preview: "motion-reduced",
  }),

  item({
    id: "login-pattern",
    title: "登录",
    english: "Login",
    category: "patterns",
    group: "账号",
    summary: "确认用户身份。",
    plain: "登录流程需要清楚展示输入、错误、忘记密码和第三方登录入口。",
    tags: ["账号", "表单", "错误"],
    useCases: ["邮箱登录", "手机号登录", "验证码登录", "SSO"],
    related: ["text-field", "password-field", "button"],
    preview: "pattern-login",
  }),
  item({
    id: "search-pattern",
    title: "搜索",
    english: "Search",
    category: "patterns",
    group: "查找",
    summary: "帮助用户找到内容。",
    plain: "搜索需要处理输入建议、无结果、加载和筛选。",
    tags: ["查找", "结果", "筛选"],
    useCases: ["站内搜索", "商品搜索", "文档搜索", "命令搜索"],
    related: ["text-field", "filter-panel", "empty-state"],
    preview: "pattern-search",
  }),
  item({
    id: "filter-pattern",
    title: "筛选",
    english: "Filter",
    category: "patterns",
    group: "查找",
    summary: "缩小内容范围。",
    plain: "筛选让用户从很多内容中快速缩小范围。",
    tags: ["商品", "后台", "列表"],
    useCases: ["价格筛选", "状态筛选", "时间筛选", "多条件筛选"],
    related: ["checkbox", "dropdown", "filter-panel"],
    preview: "pattern-filter",
  }),
  item({
    id: "upload-pattern",
    title: "上传",
    english: "Upload",
    category: "patterns",
    group: "文件",
    summary: "把本地文件交给系统处理。",
    plain: "上传流程需要展示文件选择、进度、成功、失败和重试。",
    tags: ["文件", "进度", "错误"],
    useCases: ["上传头像", "上传附件", "批量导入", "上传图片"],
    related: ["progress", "toast", "empty-state"],
    preview: "pattern-upload",
  }),
  item({
    id: "checkout-pattern",
    title: "支付结算",
    english: "Checkout",
    category: "patterns",
    group: "电商",
    summary: "完成购买或订阅。",
    plain: "结算流程要减少不确定感，清楚展示价格、地址和付款状态。",
    tags: ["电商", "支付", "表单"],
    useCases: ["购物支付", "订阅购买", "活动报名", "票务购买"],
    related: ["checkout-page", "button", "modal"],
    preview: "pattern-checkout",
  }),
  item({
    id: "delete-confirmation",
    title: "删除确认",
    english: "Delete Confirmation",
    category: "patterns",
    group: "危险操作",
    summary: "防止用户误删。",
    plain: "危险操作应该明确说明后果，并给用户取消机会。",
    tags: ["危险", "确认", "弹窗"],
    useCases: ["删除文件", "注销账号", "移除成员", "清空记录"],
    related: ["modal", "button", "toast"],
    preview: "pattern-delete",
  }),

  item({
    id: "term-modal",
    title: "弹窗",
    english: "Modal",
    category: "dictionary",
    group: "反馈",
    summary: "会盖住当前页面的弹窗。",
    plain: "看到 modal，通常意味着你需要先处理它，才能继续页面上的其他操作。",
    aliases: ["弹窗", "Dialog"],
    tags: ["弹窗", "确认"],
    related: ["modal", "toast", "drawer"],
    preview: "modal",
  }),
  item({
    id: "term-toast",
    title: "轻提示",
    english: "Toast",
    category: "dictionary",
    group: "反馈",
    summary: "短暂显示的轻提示。",
    plain: "Toast 常用来告诉你某件事刚刚成功或失败了。",
    aliases: ["轻提示", "Snackbar"],
    tags: ["提示", "反馈"],
    related: ["toast", "alert", "notification"],
    preview: "toast",
  }),
  item({
    id: "term-tab",
    title: "标签页",
    english: "Tab",
    category: "dictionary",
    group: "导航",
    summary: "同一页面中的内容切换标签。",
    plain: "Tab 帮你在一个区域里切换不同内容，不需要跳到新页面。",
    aliases: ["标签页", "页签"],
    tags: ["导航", "切换"],
    related: ["tabs", "segmented-control"],
    preview: "tabs",
  }),
  item({
    id: "term-drawer",
    title: "抽屉",
    english: "Drawer",
    category: "dictionary",
    group: "导航",
    summary: "从屏幕边缘滑出的抽屉。",
    plain: "Drawer 常用来放菜单、筛选器或临时详情。",
    aliases: ["抽屉", "侧滑面板"],
    tags: ["侧边", "面板"],
    related: ["drawer", "modal"],
    preview: "drawer",
  }),
  item({
    id: "term-skeleton",
    title: "骨架屏",
    english: "Skeleton",
    category: "dictionary",
    group: "加载",
    summary: "加载前的灰色占位。",
    plain: "Skeleton 让你知道内容正在来，并预告页面结构。",
    aliases: ["骨架屏"],
    tags: ["加载", "占位"],
    related: ["skeleton", "progress"],
    preview: "skeleton",
  }),
  item({
    id: "term-badge",
    title: "徽标",
    english: "Badge",
    category: "dictionary",
    group: "状态",
    summary: "小数字或状态标记。",
    plain: "Badge 常用来表示未读数量、新内容或状态。",
    aliases: ["徽标", "角标"],
    tags: ["状态", "数量"],
    related: ["badge", "notification"],
    preview: "badge",
  }),
];

const additionalItems = [
  item({
    id: "floating-action-button",
    title: "悬浮操作按钮",
    english: "Floating Action Button",
    category: "components",
    group: "操作",
    summary: "页面里最重要的快捷操作。",
    plain: "悬浮操作按钮通常固定在角落，用来突出创建、添加、编辑这类高频动作。",
    aliases: ["FAB", "悬浮按钮"],
    tags: ["移动端", "快捷操作", "创建"],
    variants: ["圆形 FAB", "扩展 FAB", "迷你 FAB"],
    states: ["默认", "悬停", "按下", "禁用"],
    useCases: ["新建笔记", "发布内容", "添加商品", "开始聊天"],
    related: ["button", "icon-button"],
    preview: "floating-action-button",
  }),
  item({
    id: "context-menu",
    title: "右键菜单",
    english: "Context Menu",
    category: "components",
    group: "操作",
    summary: "针对当前对象展开更多操作。",
    plain: "右键菜单和当前选中的对象有关，比如文件、图片、文本或表格行。",
    tags: ["桌面端", "更多操作", "菜单"],
    variants: ["文件菜单", "文本菜单", "表格行菜单"],
    states: ["关闭", "打开", "禁用项"],
    useCases: ["复制", "重命名", "移动", "删除"],
    related: ["menu", "dropdown", "toolbar"],
    preview: "menu",
  }),
  item({
    id: "toolbar",
    title: "工具栏",
    english: "Toolbar",
    category: "components",
    group: "操作",
    summary: "一排常用工具。",
    plain: "工具栏把常用操作放在一起，常见于编辑器、表格和绘图工具。",
    tags: ["编辑器", "后台", "工具"],
    variants: ["文字工具栏", "图标工具栏", "浮动工具栏"],
    states: ["默认", "选中", "禁用"],
    useCases: ["加粗", "保存", "筛选", "导出"],
    related: ["icon-button", "command-palette"],
    preview: "toolbar",
  }),
  item({
    id: "command-palette",
    title: "命令面板",
    english: "Command Palette",
    category: "components",
    group: "操作",
    summary: "搜索并执行功能。",
    plain: "命令面板像一个功能搜索框，适合复杂工具里快速找命令。",
    tags: ["效率", "搜索", "快捷键"],
    variants: ["全局命令", "页面命令", "最近命令"],
    states: ["打开", "搜索中", "无结果"],
    useCases: ["打开页面", "执行命令", "查找文件", "切换主题"],
    related: ["search", "modal"],
    preview: "command-palette",
  }),
  item({
    id: "textarea",
    title: "多行输入框",
    english: "Textarea",
    category: "components",
    group: "输入",
    summary: "输入较长文本。",
    plain: "多行输入框适合评论、备注、反馈和长说明。",
    tags: ["表单", "评论", "反馈"],
    variants: ["固定高度", "自动增高", "带字数统计"],
    states: ["默认", "聚焦", "错误", "禁用"],
    useCases: ["写评论", "提交反馈", "填写备注", "写简介"],
    related: ["text-field", "comment-box"],
    preview: "textarea",
  }),
  item({
    id: "search",
    title: "搜索框",
    english: "Search",
    category: "components",
    group: "输入",
    summary: "查找内容。",
    plain: "搜索框让用户输入关键词，并看到结果、建议或无结果提示。",
    tags: ["查找", "导航", "结果"],
    variants: ["普通搜索", "带建议搜索", "全局搜索", "语音搜索"],
    states: ["空", "输入中", "加载", "无结果"],
    useCases: ["搜索商品", "搜索文档", "查找联系人", "搜索命令"],
    related: ["text-field", "command-palette"],
    preview: "search",
  }),
  item({
    id: "password-field",
    title: "密码框",
    english: "Password Field",
    category: "components",
    group: "输入",
    summary: "输入隐藏内容。",
    plain: "密码框会隐藏输入内容，通常还会提供显示/隐藏按钮。",
    tags: ["登录", "安全", "表单"],
    variants: ["隐藏密码", "显示密码", "强度提示", "错误密码"],
    states: ["默认", "聚焦", "错误", "禁用"],
    useCases: ["登录", "注册", "修改密码", "二次确认"],
    related: ["text-field", "login-pattern"],
    preview: "password-field",
  }),
  item({
    id: "slider",
    title: "滑杆",
    english: "Slider",
    category: "components",
    group: "输入",
    summary: "拖动调整数值。",
    plain: "滑杆适合调音量、亮度、价格范围这类连续数值。",
    tags: ["数值", "设置", "筛选"],
    variants: ["单值滑杆", "范围滑杆", "带刻度滑杆"],
    states: ["默认", "拖动中", "禁用"],
    useCases: ["音量", "价格范围", "亮度", "进度"],
    related: ["progress", "filter-panel"],
    preview: "slider",
  }),
  item({
    id: "date-picker",
    title: "日期选择器",
    english: "Date Picker",
    category: "components",
    group: "输入",
    summary: "选择日期或时间范围。",
    plain: "日期选择器通常用于预订、筛选、日程和报表。",
    tags: ["日期", "日历", "筛选"],
    variants: ["单日选择", "日期范围", "月份选择", "时间选择"],
    states: ["打开", "已选择", "禁用", "错误"],
    useCases: ["订酒店", "筛选订单", "安排日程", "选择生日"],
    related: ["calendar", "filter-panel"],
    preview: "date-picker",
  }),
  item({
    id: "file-upload",
    title: "文件上传",
    english: "File Upload",
    category: "components",
    group: "输入",
    summary: "上传本地文件。",
    plain: "文件上传需要显示选择、进度、成功、失败和可重试入口。",
    tags: ["上传", "文件", "进度"],
    variants: ["按钮上传", "拖拽上传", "批量上传", "图片上传"],
    states: ["空", "上传中", "成功", "失败"],
    useCases: ["上传头像", "上传附件", "导入表格", "上传图片"],
    related: ["progress", "upload-pattern"],
    preview: "file-upload",
  }),
  item({
    id: "autocomplete",
    title: "自动补全",
    english: "Autocomplete",
    category: "components",
    group: "输入",
    summary: "边输入边推荐。",
    plain: "自动补全可以减少输入成本，也能避免用户输错固定名称。",
    tags: ["搜索", "表单", "建议"],
    variants: ["文字建议", "分组建议", "远程建议"],
    states: ["输入中", "加载", "无结果", "已选择"],
    useCases: ["选择城市", "搜索联系人", "填写标签", "查找命令"],
    related: ["search", "select"],
    preview: "autocomplete",
  }),
  item({
    id: "top-navigation",
    title: "顶部导航",
    english: "Top Navigation",
    category: "components",
    group: "导航",
    summary: "网站顶部主入口。",
    plain: "顶部导航让用户快速切换主要栏目，通常出现在网页最上方。",
    tags: ["导航", "网站", "桌面端"],
    variants: ["文字导航", "带搜索导航", "固定导航"],
    states: ["默认", "选中", "悬停"],
    useCases: ["官网", "文档站", "后台", "商城"],
    related: ["sidebar", "bottom-navigation"],
    preview: "top-navigation",
  }),
  item({
    id: "sidebar",
    title: "侧边栏",
    english: "Sidebar",
    category: "components",
    group: "导航",
    summary: "左侧或右侧导航。",
    plain: "侧边栏适合栏目较多、需要频繁切换的产品。",
    tags: ["后台", "文档", "设置"],
    variants: ["固定侧边栏", "可折叠侧边栏", "右侧目录"],
    states: ["展开", "收起", "选中"],
    useCases: ["后台菜单", "文档目录", "设置导航", "邮箱文件夹"],
    related: ["sidebar-layout", "drawer"],
    preview: "sidebar",
  }),
  item({
    id: "breadcrumb",
    title: "面包屑",
    english: "Breadcrumb",
    category: "components",
    group: "导航",
    summary: "显示当前位置。",
    plain: "面包屑告诉用户当前页面在网站结构中的位置，也方便回到上一层。",
    tags: ["导航", "层级", "详情页"],
    variants: ["文字面包屑", "可折叠面包屑", "带首页面包屑"],
    states: ["默认", "当前项", "悬停"],
    useCases: ["商品详情", "文档页面", "后台页面", "文件路径"],
    related: ["back-button", "top-navigation"],
    preview: "breadcrumb",
  }),
  item({
    id: "pagination",
    title: "分页",
    english: "Pagination",
    category: "components",
    group: "导航",
    summary: "翻页浏览内容。",
    plain: "分页适合结果很多但不希望一次加载全部的列表。",
    tags: ["列表", "搜索", "表格"],
    variants: ["数字分页", "上一页下一页", "加载更多"],
    states: ["当前页", "禁用", "悬停"],
    useCases: ["搜索结果", "订单列表", "评论列表", "文章列表"],
    related: ["table", "search-results-page"],
    preview: "pagination",
  }),
  item({
    id: "stepper",
    title: "步骤条",
    english: "Stepper",
    category: "components",
    group: "导航",
    summary: "分步骤完成任务。",
    plain: "步骤条让用户知道流程到了哪一步，还剩几步。",
    tags: ["流程", "注册", "支付"],
    variants: ["横向步骤", "纵向步骤", "带状态步骤"],
    states: ["未完成", "当前", "完成", "错误"],
    useCases: ["注册", "支付", "问卷", "导入数据"],
    related: ["wizard", "checkout-page"],
    preview: "stepper",
  }),
  item({
    id: "bottom-navigation",
    title: "底部导航",
    english: "Bottom Navigation",
    category: "components",
    group: "导航",
    summary: "移动端底部主导航。",
    plain: "底部导航适合移动端 3 到 5 个高频主入口。",
    tags: ["移动端", "导航", "App"],
    variants: ["图标底栏", "图文底栏", "带徽标底栏"],
    states: ["默认", "选中", "禁用"],
    useCases: ["首页", "搜索", "消息", "我的"],
    related: ["top-navigation", "badge"],
    preview: "bottom-navigation",
  }),
  item({
    id: "back-button",
    title: "返回按钮",
    english: "Back Button",
    category: "components",
    group: "导航",
    summary: "回到上一层。",
    plain: "返回按钮应该让用户明确知道可以离开当前详情或流程。",
    tags: ["导航", "移动端", "详情"],
    variants: ["文字返回", "图标返回", "浏览器返回"],
    states: ["默认", "悬停", "禁用"],
    useCases: ["详情页", "表单页", "二级页面", "移动端流程"],
    related: ["breadcrumb", "drawer"],
    preview: "back-button",
  }),
  item({
    id: "list",
    title: "列表",
    english: "List",
    category: "components",
    group: "展示",
    summary: "一条一条展示内容。",
    plain: "列表适合连续浏览类似内容，比如消息、订单和搜索结果。",
    tags: ["展示", "搜索", "后台"],
    variants: ["普通列表", "带头像列表", "可选列表", "分组列表"],
    states: ["默认", "选中", "加载", "空"],
    useCases: ["消息列表", "订单列表", "联系人", "搜索结果"],
    related: ["card", "table"],
    preview: "list",
  }),
  item({
    id: "avatar",
    title: "头像",
    english: "Avatar",
    category: "components",
    group: "展示",
    summary: "表示用户或对象。",
    plain: "头像帮助用户快速识别人、团队或空间。",
    tags: ["用户", "社交", "账号"],
    variants: ["图片头像", "文字头像", "头像组", "带状态头像"],
    states: ["在线", "离线", "加载", "缺省"],
    useCases: ["个人资料", "评论", "成员列表", "聊天"],
    related: ["badge", "chat-bubble"],
    preview: "avatar",
  }),
  item({
    id: "tag",
    title: "标签",
    english: "Tag",
    category: "components",
    group: "展示",
    summary: "给内容分类。",
    plain: "标签用于标记主题、状态、分类或可筛选条件。",
    tags: ["分类", "筛选", "状态"],
    variants: ["普通标签", "可关闭标签", "可选标签", "状态标签"],
    states: ["默认", "选中", "禁用"],
    useCases: ["文章分类", "商品属性", "任务状态", "筛选条件"],
    related: ["badge", "filter-panel"],
    preview: "tag",
  }),
  item({
    id: "popover",
    title: "浮层",
    english: "Popover",
    category: "components",
    group: "展示",
    summary: "临时显示更多内容。",
    plain: "浮层比 Tooltip 内容更多，但通常不打断整个页面。",
    tags: ["更多信息", "浮层", "临时"],
    variants: ["信息浮层", "操作浮层", "选择浮层"],
    states: ["隐藏", "显示", "关闭"],
    useCases: ["用户卡片", "小设置", "选择日期", "查看说明"],
    related: ["tooltip", "modal"],
    preview: "popover",
  }),
  item({
    id: "carousel",
    title: "轮播",
    english: "Carousel",
    category: "components",
    group: "展示",
    summary: "横向切换多张内容。",
    plain: "轮播适合少量视觉内容切换，不适合隐藏重要信息。",
    tags: ["图片", "营销", "内容"],
    variants: ["自动轮播", "手动轮播", "卡片轮播"],
    states: ["当前项", "上一项", "下一项"],
    useCases: ["活动 Banner", "作品展示", "图片浏览", "推荐内容"],
    related: ["card", "pagination"],
    preview: "carousel",
  }),
  item({
    id: "timeline",
    title: "时间线",
    english: "Timeline",
    category: "components",
    group: "展示",
    summary: "按时间展示事件。",
    plain: "时间线适合展示进度、历史记录、物流和版本变化。",
    tags: ["时间", "记录", "进度"],
    variants: ["纵向时间线", "横向时间线", "状态时间线"],
    states: ["已完成", "当前", "未来"],
    useCases: ["物流", "审批", "版本记录", "活动日程"],
    related: ["stepper", "progress"],
    preview: "timeline",
  }),
  item({
    id: "calendar",
    title: "日历",
    english: "Calendar",
    category: "components",
    group: "展示",
    summary: "日期视图。",
    plain: "日历帮助用户按天、周、月查看事件或选择日期。",
    tags: ["日期", "日程", "预订"],
    variants: ["月视图", "周视图", "日程视图", "范围选择"],
    states: ["今天", "选中", "禁用", "有事件"],
    useCases: ["排班", "预订", "活动", "日程管理"],
    related: ["date-picker", "timeline"],
    preview: "calendar",
  }),
  item({
    id: "alert",
    title: "警告",
    english: "Alert",
    category: "components",
    group: "反馈",
    summary: "显眼的重要提示。",
    plain: "Alert 适合显示需要被认真看到的信息，比如错误、风险或系统通知。",
    tags: ["警告", "错误", "提示"],
    variants: ["信息", "成功", "警告", "危险"],
    states: ["显示", "关闭", "带操作"],
    useCases: ["表单错误", "系统维护", "权限不足", "支付失败"],
    related: ["toast", "modal"],
    preview: "alert",
  }),
  item({
    id: "confirmation",
    title: "确认框",
    english: "Confirmation",
    category: "components",
    group: "反馈",
    summary: "防止误操作。",
    plain: "确认框用于删除、退出、付款等有明显后果的操作。",
    tags: ["危险", "确认", "弹窗"],
    variants: ["删除确认", "退出确认", "付款确认"],
    states: ["等待确认", "处理中", "取消"],
    useCases: ["删除文件", "退出登录", "清空记录", "取消订单"],
    related: ["modal", "button"],
    preview: "confirmation",
  }),
  item({
    id: "spinner",
    title: "加载圈",
    english: "Spinner",
    category: "components",
    group: "反馈",
    summary: "表示正在加载。",
    plain: "加载圈适合短时间等待，长时间加载更适合进度条或骨架屏。",
    tags: ["加载", "等待", "反馈"],
    variants: ["小加载圈", "按钮加载圈", "页面加载圈"],
    states: ["旋转", "停止"],
    useCases: ["提交中", "切换中", "加载更多", "刷新"],
    related: ["progress", "skeleton"],
    preview: "spinner",
  }),
  item({
    id: "success-state",
    title: "成功状态",
    english: "Success State",
    category: "components",
    group: "反馈",
    summary: "操作完成反馈。",
    plain: "成功状态让用户确信任务已经完成，可以继续下一步。",
    tags: ["成功", "完成", "反馈"],
    variants: ["成功页", "成功提示", "按钮成功"],
    states: ["完成", "可继续", "可返回"],
    useCases: ["支付成功", "保存成功", "发布成功", "提交成功"],
    related: ["toast", "button"],
    preview: "success-state",
  }),
  item({
    id: "error-state",
    title: "错误状态",
    english: "Error State",
    category: "components",
    group: "反馈",
    summary: "操作失败说明。",
    plain: "错误状态要说明哪里错了，以及用户怎么恢复。",
    tags: ["错误", "失败", "重试"],
    variants: ["表单错误", "页面错误", "网络错误", "权限错误"],
    states: ["失败", "可重试", "可返回"],
    useCases: ["上传失败", "付款失败", "网络失败", "权限不足"],
    related: ["alert", "toast"],
    preview: "error-state",
  }),
  item({
    id: "notification",
    title: "通知",
    english: "Notification",
    category: "components",
    group: "反馈",
    summary: "告诉用户有新消息。",
    plain: "通知通常比 Toast 更持久，可能进入通知中心或消息列表。",
    tags: ["消息", "提醒", "状态"],
    variants: ["站内通知", "系统通知", "未读通知"],
    states: ["未读", "已读", "关闭"],
    useCases: ["新消息", "审批提醒", "系统公告", "任务提醒"],
    related: ["badge", "toast"],
    preview: "notification",
  }),
  item({
    id: "form",
    title: "表单",
    english: "Form",
    category: "components",
    group: "复合",
    summary: "一组输入项。",
    plain: "表单把多个输入、选择和提交动作组合成一个任务。",
    tags: ["输入", "提交", "错误"],
    variants: ["单列表单", "分组表单", "分步表单"],
    states: ["填写中", "错误", "提交中", "成功"],
    useCases: ["注册", "资料编辑", "反馈提交", "地址填写"],
    related: ["text-field", "button"],
    preview: "form",
  }),
  item({
    id: "data-grid",
    title: "数据表格",
    english: "Data Grid",
    category: "components",
    group: "复合",
    summary: "可排序、筛选、编辑的数据表。",
    plain: "数据表格比普通表格更像工具，适合大量数据管理。",
    tags: ["后台", "数据", "编辑"],
    variants: ["可排序", "可筛选", "可编辑", "可选择"],
    states: ["加载", "空", "选中", "错误"],
    useCases: ["订单管理", "成员管理", "库存管理", "报表"],
    related: ["table", "filter-panel"],
    preview: "data-grid",
  }),
  item({
    id: "filter-panel",
    title: "筛选面板",
    english: "Filter Panel",
    category: "components",
    group: "复合",
    summary: "缩小内容范围。",
    plain: "筛选面板把多个筛选条件集中放在一起。",
    tags: ["筛选", "列表", "商品"],
    variants: ["侧边筛选", "顶部筛选", "抽屉筛选"],
    states: ["未筛选", "已筛选", "清空"],
    useCases: ["商品筛选", "订单筛选", "任务筛选", "搜索结果"],
    related: ["checkbox", "dropdown"],
    preview: "filter-panel",
  }),
  item({
    id: "sort-control",
    title: "排序控件",
    english: "Sort Control",
    category: "components",
    group: "复合",
    summary: "改变内容顺序。",
    plain: "排序控件让用户按时间、价格、热度或名称重新排列结果。",
    tags: ["排序", "列表", "搜索"],
    variants: ["下拉排序", "表头排序", "分段排序"],
    states: ["升序", "降序", "默认"],
    useCases: ["按价格", "按时间", "按热度", "按评分"],
    related: ["dropdown", "table"],
    preview: "sort-control",
  }),
  item({
    id: "media-player",
    title: "媒体播放器",
    english: "Media Player",
    category: "components",
    group: "复合",
    summary: "播放音视频。",
    plain: "播放器需要包含播放、暂停、进度、音量和全屏等基础控制。",
    tags: ["视频", "音频", "控制"],
    variants: ["音频播放器", "视频播放器", "迷你播放器"],
    states: ["播放", "暂停", "缓冲", "结束"],
    useCases: ["课程视频", "音乐", "直播回放", "产品演示"],
    related: ["slider", "progress"],
    preview: "media-player",
  }),
  item({
    id: "chat-bubble",
    title: "聊天气泡",
    english: "Chat Bubble",
    category: "components",
    group: "复合",
    summary: "展示对话内容。",
    plain: "聊天气泡区分自己和对方的消息，也显示状态和时间。",
    tags: ["聊天", "消息", "AI"],
    variants: ["用户气泡", "助手气泡", "系统消息"],
    states: ["发送中", "已发送", "失败"],
    useCases: ["客服", "AI Chatbot", "私信", "评论回复"],
    related: ["avatar", "notification"],
    preview: "chat-bubble",
  }),
  item({
    id: "comment-box",
    title: "评论框",
    english: "Comment Box",
    category: "components",
    group: "复合",
    summary: "输入并发布评论。",
    plain: "评论框通常由头像、输入区、发布按钮和回复状态组成。",
    tags: ["评论", "社交", "输入"],
    variants: ["基础评论框", "回复评论框", "带附件评论框"],
    states: ["输入中", "提交中", "成功", "失败"],
    useCases: ["文章评论", "商品评价", "任务讨论", "社交回复"],
    related: ["textarea", "button"],
    preview: "comment-box",
  }),
  item({
    id: "rating",
    title: "评分",
    english: "Rating",
    category: "components",
    group: "复合",
    summary: "星级或数值评价。",
    plain: "评分让用户快速表达满意程度，常见于商品、服务和内容评价。",
    tags: ["评价", "电商", "反馈"],
    variants: ["星级评分", "数字评分", "表情评分"],
    states: ["未评分", "悬停", "已评分", "只读"],
    useCases: ["商品评价", "课程评价", "服务满意度", "内容反馈"],
    related: ["comment-box", "badge"],
    preview: "rating",
  }),
  item({
    id: "shopping-cart",
    title: "购物车",
    english: "Shopping Cart",
    category: "components",
    group: "复合",
    summary: "商品选择与结算。",
    plain: "购物车需要展示商品、数量、价格、优惠和结算入口。",
    tags: ["电商", "结算", "支付"],
    variants: ["页面购物车", "迷你购物车", "抽屉购物车"],
    states: ["空", "有商品", "加载", "错误"],
    useCases: ["电商购买", "订阅套餐", "活动票务", "课程购买"],
    related: ["checkout-page", "button"],
    preview: "shopping-cart",
  }),
  item({
    id: "three-column",
    title: "三栏布局",
    english: "Three Column",
    category: "layouts",
    group: "复杂工具",
    summary: "三块区域并列承载不同任务。",
    plain: "三栏布局适合邮箱、后台和复杂工具，一般包含导航、列表和详情。",
    tags: ["邮箱", "后台", "工具"],
    useCases: ["邮箱", "项目管理", "开发工具", "客服系统"],
    related: ["sidebar-layout", "master-detail"],
    preview: "layout-three",
  }),
  item({
    id: "sticky-header",
    title: "吸顶顶部",
    english: "Sticky Header",
    category: "layouts",
    group: "滚动",
    summary: "滚动时顶部固定。",
    plain: "吸顶顶部让主要导航或操作在滚动中保持可见。",
    tags: ["滚动", "导航", "网页"],
    useCases: ["文档站", "电商", "后台", "长页面"],
    related: ["top-navigation", "sticky-sidebar"],
    preview: "layout-sticky-header",
  }),
  item({
    id: "sticky-sidebar",
    title: "吸附侧栏",
    english: "Sticky Sidebar",
    category: "layouts",
    group: "滚动",
    summary: "滚动时侧栏保持可见。",
    plain: "吸附侧栏常用于文档目录、筛选器和页面导航。",
    tags: ["目录", "筛选", "滚动"],
    useCases: ["文档目录", "商品筛选", "文章目录", "帮助中心"],
    related: ["sidebar", "filter-panel"],
    preview: "layout-sticky-sidebar",
  }),
  item({
    id: "masonry",
    title: "瀑布流",
    english: "Masonry",
    category: "layouts",
    group: "图片",
    summary: "高低不同的内容错落排列。",
    plain: "瀑布流适合图片、灵感和作品集，但不适合需要严格比较的数据。",
    tags: ["图片", "灵感", "作品"],
    useCases: ["图片社区", "灵感库", "作品集", "商品图集"],
    related: ["card-grid", "carousel"],
    preview: "layout-masonry",
  }),
  item({
    id: "split-pane",
    title: "分割面板",
    english: "Split Pane",
    category: "layouts",
    group: "工具",
    summary: "可调整大小的并列区域。",
    plain: "分割面板常用于编辑器和开发工具，一边编辑一边预览。",
    tags: ["编辑器", "开发工具", "预览"],
    useCases: ["代码编辑器", "邮件编辑", "设计工具", "文档预览"],
    related: ["three-column", "toolbar"],
    preview: "layout-split",
  }),
  item({
    id: "wizard",
    title: "向导式布局",
    english: "Wizard",
    category: "layouts",
    group: "流程",
    summary: "分步骤完成复杂任务。",
    plain: "向导式布局把复杂任务拆成几步，让用户一步一步完成。",
    tags: ["注册", "支付", "问卷"],
    useCases: ["注册", "支付", "导入数据", "问卷"],
    related: ["stepper", "form"],
    preview: "layout-wizard",
  }),
  item({
    id: "fullscreen-modal",
    title: "全屏弹窗",
    english: "Fullscreen Modal",
    category: "layouts",
    group: "流程",
    summary: "用完整屏幕承载临时任务。",
    plain: "全屏弹窗适合移动端复杂编辑或需要沉浸处理的任务。",
    tags: ["移动端", "编辑", "弹窗"],
    useCases: ["复杂编辑", "移动端发布", "资料填写", "图片编辑"],
    related: ["modal", "drawer"],
    preview: "layout-fullscreen-modal",
  }),
  item({
    id: "landing-page",
    title: "落地页",
    english: "Landing Page",
    category: "layouts",
    group: "营销",
    summary: "介绍产品或活动并促成行动。",
    plain: "落地页通常包含主标题、卖点、证明、行动按钮和常见问题。",
    tags: ["营销", "官网", "转化"],
    useCases: ["产品官网", "活动页", "下载页", "报名页"],
    related: ["button", "card-grid"],
    preview: "layout-landing",
  }),
  item({
    id: "profile-page",
    title: "资料页",
    english: "Profile Page",
    category: "layouts",
    group: "用户",
    summary: "展示用户或对象资料。",
    plain: "资料页用于展示头像、简介、数据、作品和操作入口。",
    tags: ["用户", "社交", "账号"],
    useCases: ["个人主页", "团队主页", "作者资料", "商家资料"],
    related: ["avatar", "card"],
    preview: "layout-profile",
  }),
  item({
    id: "search-results-page",
    title: "搜索结果页",
    english: "Search Results Page",
    category: "layouts",
    group: "查找",
    summary: "展示搜索后的结果。",
    plain: "搜索结果页需要有搜索框、结果列表、筛选和无结果状态。",
    tags: ["搜索", "筛选", "结果"],
    useCases: ["站内搜索", "商品搜索", "文档搜索", "帮助搜索"],
    related: ["search", "filter-panel"],
    preview: "layout-search-results",
  }),
  item({
    id: "detail-page",
    title: "详情页",
    english: "Detail Page",
    category: "layouts",
    group: "详情",
    summary: "展示一个对象的完整信息。",
    plain: "详情页适合商品、文章、用户、订单和任务。",
    tags: ["详情", "商品", "文章"],
    useCases: ["商品详情", "文章详情", "订单详情", "用户详情"],
    related: ["two-column", "tabs"],
    preview: "layout-detail",
  }),
  item({
    id: "border",
    title: "边框",
    english: "Border",
    category: "styles",
    group: "分隔",
    summary: "用线条建立边界。",
    plain: "边框适合轻量分隔，比阴影更克制。",
    tags: ["分隔", "卡片", "输入"],
    variants: ["细边框", "虚线边框", "强调边框"],
    related: ["shadow", "divider"],
    preview: "style-border",
  }),
  item({
    id: "gradient",
    title: "渐变",
    english: "Gradient",
    category: "styles",
    group: "视觉",
    summary: "颜色之间平滑过渡。",
    plain: "渐变可以制造层次和品牌感，但用多了会显得吵。",
    tags: ["品牌", "背景", "按钮"],
    variants: ["按钮渐变", "背景渐变", "卡片渐变"],
    related: ["color", "emphasis"],
    preview: "style-gradient",
  }),
  item({
    id: "transparency",
    title: "透明感",
    english: "Transparency",
    category: "styles",
    group: "材质",
    summary: "半透明或毛玻璃效果。",
    plain: "透明感适合浮层和系统界面，但必须保证文字可读。",
    tags: ["毛玻璃", "浮层", "模糊"],
    variants: ["半透明", "毛玻璃", "模糊背景"],
    related: ["popover", "modal"],
    preview: "style-transparency",
  }),
  item({
    id: "icon-style",
    title: "图标风格",
    english: "Icon Style",
    category: "styles",
    group: "图标",
    summary: "线性、实心或双色图标。",
    plain: "同一个界面里的图标风格应该一致，不要混用太多样式。",
    tags: ["图标", "导航", "按钮"],
    variants: ["线性", "实心", "双色", "圆角"],
    related: ["icon-button", "toolbar"],
    preview: "style-icons",
  }),
  item({
    id: "divider",
    title: "分割方式",
    english: "Divider",
    category: "styles",
    group: "分隔",
    summary: "用线、留白、卡片或色块分组。",
    plain: "好的分割方式让用户知道哪些信息属于一组。",
    tags: ["分组", "排版", "列表"],
    variants: ["分割线", "留白", "卡片", "色块"],
    related: ["spacing", "border"],
    preview: "style-divider",
  }),
  item({
    id: "emphasis",
    title: "强调方式",
    english: "Emphasis",
    category: "styles",
    group: "重点",
    summary: "突出最重要的信息。",
    plain: "强调可以用粗体、背景、徽标或颜色，但一屏重点不要太多。",
    tags: ["重点", "高亮", "状态"],
    variants: ["高亮", "徽标", "加粗", "背景色"],
    related: ["badge", "color"],
    preview: "style-emphasis",
  }),
  item({
    id: "theme",
    title: "主题",
    english: "Theme",
    category: "styles",
    group: "主题",
    summary: "明亮、暗黑或高对比模式。",
    plain: "主题不是换背景色这么简单，还要重新检查文字、边框和状态。",
    tags: ["明亮", "暗黑", "高对比"],
    variants: ["明亮模式", "暗黑模式", "高对比模式"],
    related: ["dark-mode", "color"],
    preview: "style-theme",
  }),
  item({
    id: "brand-feel",
    title: "品牌感",
    english: "Brand Feel",
    category: "styles",
    group: "气质",
    summary: "界面给人的第一印象。",
    plain: "品牌感可以是企业、科技、可爱、复古、游戏化或极简。",
    tags: ["品牌", "气质", "视觉"],
    variants: ["企业", "科技", "可爱", "复古", "游戏化"],
    related: ["color", "typography"],
    preview: "style-brand",
  }),
  item({
    id: "fade-motion",
    title: "淡入淡出",
    english: "Fade",
    category: "motion",
    group: "切换",
    summary: "内容轻轻出现或消失。",
    plain: "淡入淡出适合同一区域内容替换，感觉安静不打扰。",
    tags: ["进入", "离开", "切换"],
    useCases: ["Toast 消失", "内容切换", "弹窗出现"],
    related: ["toast", "modal"],
    preview: "motion-fade",
  }),
  item({
    id: "slide-motion",
    title: "滑入滑出",
    english: "Slide",
    category: "motion",
    group: "空间",
    summary: "从某个方向进入或离开。",
    plain: "滑动动效能暗示内容来自哪里，比如抽屉从侧边滑出。",
    tags: ["抽屉", "页面", "空间"],
    useCases: ["抽屉", "页面切换", "通知进入"],
    related: ["drawer", "page-transition"],
    preview: "motion-slide",
  }),
  item({
    id: "scale-motion",
    title: "缩放动效",
    english: "Scale",
    category: "motion",
    group: "反馈",
    summary: "轻微变大或变小。",
    plain: "缩放常用于点击反馈、弹窗出现和卡片选中。",
    tags: ["点击", "弹窗", "卡片"],
    useCases: ["按钮按下", "弹窗打开", "卡片选中"],
    related: ["press-motion", "modal"],
    preview: "motion-scale",
  }),
  item({
    id: "page-transition",
    title: "页面切换",
    english: "Page Transition",
    category: "motion",
    group: "导航",
    summary: "页面之间的过渡。",
    plain: "页面切换要帮助用户理解前进、返回和层级关系。",
    tags: ["页面", "导航", "层级"],
    useCases: ["进入详情", "返回列表", "切换栏目"],
    related: ["slide-motion", "breadcrumb"],
    preview: "motion-page",
  }),
  item({
    id: "attention-motion",
    title: "注意力动效",
    english: "Attention Motion",
    category: "motion",
    group: "提醒",
    summary: "提醒用户注意。",
    plain: "注意力动效应该少用，只提醒真正重要的变化。",
    tags: ["提醒", "徽标", "通知"],
    useCases: ["新消息", "未读徽标", "重要按钮"],
    related: ["badge", "notification"],
    preview: "motion-attention",
  }),
  item({
    id: "spatial-motion",
    title: "空间动效",
    english: "Spatial Motion",
    category: "motion",
    group: "空间",
    summary: "表达位置关系。",
    plain: "空间动效让用户知道一个面板、卡片或详情从哪里来。",
    tags: ["位置", "层级", "详情"],
    useCases: ["卡片展开", "抽屉滑出", "详情进入"],
    related: ["drawer", "master-detail"],
    preview: "motion-spatial",
  }),
  item({
    id: "list-motion",
    title: "列表动效",
    english: "List Motion",
    category: "motion",
    group: "数据",
    summary: "表达数据变化。",
    plain: "列表新增、删除或排序时，轻微动效能减少突兀感。",
    tags: ["列表", "数据", "排序"],
    useCases: ["插入新项", "删除条目", "排序变化"],
    related: ["list", "sort-control"],
    preview: "motion-list",
  }),
  item({
    id: "drag-motion",
    title: "拖拽动效",
    english: "Drag Motion",
    category: "motion",
    group: "手势",
    summary: "对象跟随手指或鼠标移动。",
    plain: "拖拽动效应该实时反馈，并在释放后清楚地落到目标位置。",
    tags: ["拖拽", "排序", "移动"],
    useCases: ["拖拽排序", "移动文件", "拖拽上传"],
    related: ["file-upload", "list-motion"],
    preview: "motion-drag",
  }),
  item({
    id: "signup-pattern",
    title: "注册",
    english: "Signup",
    category: "patterns",
    group: "账号",
    summary: "创建新账号。",
    plain: "注册流程需要解释要填什么、为什么填，以及如何处理错误。",
    tags: ["账号", "表单", "引导"],
    useCases: ["邮箱注册", "手机号注册", "邀请注册"],
    related: ["form", "stepper"],
    preview: "pattern-signup",
  }),
  item({
    id: "sort-pattern",
    title: "排序",
    english: "Sort",
    category: "patterns",
    group: "查找",
    summary: "改变结果顺序。",
    plain: "排序让用户按自己关心的维度看内容，比如最新、最热、价格。",
    tags: ["搜索", "列表", "商品"],
    useCases: ["按最新", "按价格", "按评分", "按热度"],
    related: ["sort-control", "dropdown"],
    preview: "pattern-sort",
  }),
  item({
    id: "onboarding-pattern",
    title: "新手引导",
    english: "Onboarding",
    category: "patterns",
    group: "引导",
    summary: "帮助新用户开始使用。",
    plain: "新手引导应该尽快让用户完成第一件有价值的事。",
    tags: ["引导", "注册", "首次使用"],
    useCases: ["欢迎页", "权限说明", "功能介绍", "首个任务"],
    related: ["wizard", "stepper"],
    preview: "pattern-onboarding",
  }),
  item({
    id: "settings-pattern",
    title: "设置",
    english: "Settings",
    category: "patterns",
    group: "账户",
    summary: "管理账户和偏好。",
    plain: "设置场景要让用户快速找到选项，并理解开启或关闭的影响。",
    tags: ["账户", "偏好", "开关"],
    useCases: ["通知设置", "隐私设置", "安全设置", "主题设置"],
    related: ["settings-page", "switch"],
    preview: "pattern-settings",
  }),
  item({
    id: "form-fill-pattern",
    title: "表单填写",
    english: "Form Filling",
    category: "patterns",
    group: "输入",
    summary: "完成一组信息填写。",
    plain: "表单填写要有清楚标签、帮助文字、错误提示和提交反馈。",
    tags: ["表单", "错误", "提交"],
    useCases: ["收货地址", "资料编辑", "问卷", "申请表"],
    related: ["form", "text-field"],
    preview: "pattern-form",
  }),
  item({
    id: "error-message-pattern",
    title: "错误提示",
    english: "Error Message",
    category: "patterns",
    group: "反馈",
    summary: "告诉用户哪里出了问题。",
    plain: "错误提示要说明原因和恢复方式，不要只写“失败”。",
    tags: ["错误", "表单", "恢复"],
    useCases: ["密码错误", "网络失败", "权限不足", "上传失败"],
    related: ["alert", "error-state"],
    preview: "pattern-error",
  }),
  item({
    id: "term-tooltip",
    title: "提示气泡",
    english: "Tooltip",
    category: "dictionary",
    group: "说明",
    summary: "悬停时出现的小说明。",
    plain: "Tooltip 常用于解释图标、短标签和快捷键。",
    aliases: ["提示气泡"],
    related: ["tooltip", "popover"],
    preview: "tooltip",
  }),
  item({
    id: "term-popover",
    title: "浮层",
    english: "Popover",
    category: "dictionary",
    group: "浮层",
    summary: "临时显示更多内容的浮层。",
    plain: "Popover 比 Tooltip 内容更多，通常可以放小操作或小表单。",
    aliases: ["浮层"],
    related: ["popover", "tooltip"],
    preview: "popover",
  }),
  item({
    id: "term-accordion",
    title: "手风琴",
    english: "Accordion",
    category: "dictionary",
    group: "展示",
    summary: "展开和收起内容的组件。",
    plain: "Accordion 常用于 FAQ、设置分组和长说明。",
    aliases: ["手风琴"],
    related: ["accordion"],
    preview: "accordion",
  }),
  item({
    id: "term-carousel",
    title: "轮播",
    english: "Carousel",
    category: "dictionary",
    group: "展示",
    summary: "横向轮流展示内容。",
    plain: "Carousel 常见于 Banner、图片和推荐内容。",
    aliases: ["轮播"],
    related: ["carousel"],
    preview: "carousel",
  }),
  item({
    id: "term-pagination",
    title: "分页",
    english: "Pagination",
    category: "dictionary",
    group: "导航",
    summary: "分页浏览内容。",
    plain: "Pagination 让用户在很多页结果之间切换。",
    aliases: ["分页"],
    related: ["pagination"],
    preview: "pagination",
  }),
  item({
    id: "term-breadcrumb",
    title: "面包屑",
    english: "Breadcrumb",
    category: "dictionary",
    group: "导航",
    summary: "显示当前位置的路径。",
    plain: "Breadcrumb 像面包屑路径，帮助用户回到上一级。",
    aliases: ["面包屑"],
    related: ["breadcrumb"],
    preview: "breadcrumb",
  }),
  item({
    id: "term-cta",
    title: "行动号召",
    english: "CTA",
    category: "dictionary",
    group: "操作",
    summary: "希望用户点击的主要行动。",
    plain: "CTA 通常是页面最重要的按钮，比如立即购买、开始使用。",
    aliases: ["行动号召", "主按钮"],
    related: ["button"],
    preview: "button",
  }),
  item({
    id: "term-fab",
    title: "悬浮操作按钮",
    english: "FAB",
    category: "dictionary",
    group: "操作",
    summary: "悬浮操作按钮。",
    plain: "FAB 是 Floating Action Button 的缩写，常见于移动端主操作。",
    aliases: ["悬浮按钮"],
    related: ["floating-action-button"],
    preview: "floating-action-button",
  }),
];

export const uiItems = [...coreItems, ...additionalItems];

export const quickQuestions = [
  "按钮和链接有什么区别？",
  "什么是弹窗？",
  "什么时候使用 Toast？",
  "为什么加载时会有骨架屏？",
  "什么是面包屑导航？",
];

export const categoryDescriptions = {
  components: "按钮、输入框、弹窗、标签页、Toast 等界面零件。",
  layouts: "单列、双栏、侧边栏、仪表盘、结算页等页面骨架。",
  styles: "圆角、阴影、留白、字体层级、颜色和密度。",
  motion: "点击、悬停、加载、成功、错误、展开和减少动效。",
  patterns: "登录、搜索、筛选、上传、支付、删除确认等常见流程。",
  dictionary: "弹窗 Modal、轻提示 Toast、标签页 Tab、抽屉 Drawer 等术语。",
};

export function findItem(id) {
  return uiItems.find((entry) => entry.id === id) || uiItems[0];
}
